---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{NAMESPACE}}"
  name: ephemeral-kopf-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeral-kopf-clusterrole
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: ["list", "watch"]
  - apiGroups: ["kopf.dev"]
    resources: ["ephemeralvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "remove", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "remove", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ephemeral-kopf-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ephemeral-kopf-clusterrole
subjects:
  - kind: ServiceAccount
    name: ephemeral-kopf-serviceaccount
    namespace: "{{NAMESPACE}}"
